package storage

import (
	"encoding/json"
	"strings"
	"time"
)

// RequeueRecord is the durable, minimal projection of an import request that
// was bounced back to the queue because the debrid reported
// too_many_active_downloads. It carries only the fields needed to rebuild an
// importable request after a process restart.
//
// The live *arr.Arr is deliberately NOT serialized: it holds an HTTP client,
// a token, and a host that all belong to the running config. Only Arr.Name is
// persisted; the drain re-resolves it against the currently configured arrs
// (and discards the record if it no longer resolves, rather than reviving a
// grab against a deleted/renamed arr).
//
// Encoding note: the queue/entries buckets use protobuf, but those messages
// are generated by an external protoc-gen-go toolchain that is not part of
// this build (the .pb.go files are checked in, not generated here). hybrid
// Store.Put is byte-agnostic, so this small internal record is encoded with
// encoding/json via its struct tags - stdlib, no extra dependency, and a
// faithful round-trip is all a recovery record needs.
type RequeueRecord struct {
	// Magnet projection (only the recoverable fields - File bytes are dropped).
	MagnetLink     string `json:"magnetLink"`
	MagnetName     string `json:"magnetName"`
	MagnetInfoHash string `json:"magnetInfoHash"`
	MagnetSize     int64  `json:"magnetSize"`

	ArrName          string `json:"arrName"`
	Action           string `json:"action"`
	DownloadFolder   string `json:"downloadFolder"`
	DownloadUncached *bool  `json:"downloadUncached,omitempty"`
	CallBackUrl      string `json:"callBackUrl,omitempty"`
	SkipMultiSeason  bool   `json:"skipMultiSeason,omitempty"`
	SelectedDebrid   string `json:"selectedDebrid,omitempty"`
	Type             string `json:"type"`

	// PersistedAt anchors the self-healing TTL in DrainPersistedRequeue: a
	// record older than 2*removeStalledAfter cannot represent a still-valid
	// requeue (the stalled remover would have reaped its entry), so the drain
	// discards it instead of re-spawning a zombie grab.
	PersistedAt time.Time `json:"persistedAt"`
}

// PutRequeue persists (or overwrites) a requeue record keyed by lowercased
// infohash. Mirrors UpdateQueue's keying convention (strings.ToLower) so a
// re-push of the same hash de-dupes rather than accumulating duplicates.
func (s *Storage) PutRequeue(key string, r *RequeueRecord) error {
	data, err := json.Marshal(r)
	if err != nil {
		return err
	}
	return s.requeue.Put(strings.ToLower(key), data, nil)
}

// GetRequeue retrieves a single requeue record by infohash.
func (s *Storage) GetRequeue(key string) (*RequeueRecord, error) {
	data, err := s.requeue.Get(strings.ToLower(key))
	if err != nil {
		return nil, err
	}
	var r RequeueRecord
	if err := json.Unmarshal(data, &r); err != nil {
		return nil, err
	}
	return &r, nil
}

// ForEachRequeue iterates every persisted requeue record. A decode failure on
// one record is skipped (best-effort) so a single corrupt entry can't block
// recovery of the rest.
func (s *Storage) ForEachRequeue(fn func(key string, r *RequeueRecord) error) error {
	return s.requeue.ForEach(func(key string, value []byte) error {
		var r RequeueRecord
		if err := json.Unmarshal(value, &r); err != nil {
			return nil
		}
		return fn(key, &r)
	})
}

// DeleteRequeue removes a persisted requeue record by infohash.
func (s *Storage) DeleteRequeue(key string) error {
	return s.requeue.Delete(strings.ToLower(key))
}

// RequeueOwnedByEntry reports whether a live entry already owns this infohash
// in EITHER the entries bucket or the queue bucket. The self-healing drain
// uses this to discard a persisted requeue whose grab is already in flight
// (preventing a duplicate/zombie grab on restart). Both raw and lowercased
// keys are probed because the entries bucket is keyed by the raw infohash
// while the queue bucket lowercases it (see UpdateQueue).
func (s *Storage) RequeueOwnedByEntry(infohash string) bool {
	raw := infohash
	lower := strings.ToLower(infohash)
	if s.entries.Exists(raw) || s.entries.Exists(lower) {
		return true
	}
	if _, err := s.GetQueued(lower); err == nil {
		return true
	}
	return false
}
