package storage

import (
	"encoding/json"
	"strings"
	"time"
)

// TombstoneRecord is the durable record of a deliberate deletion. It is keyed
// by lowercased infohash and used by the sync path to prevent re-adoption of
// an item the user explicitly removed.
//
// Encoding note: the queue/entries buckets use protobuf, but those messages
// are generated by an external protoc-gen-go toolchain that is not part of
// this build (the .pb.go files are checked in, not generated here). hybrid
// Store.Put is byte-agnostic, so this small internal record is encoded with
// encoding/json via its struct tags - stdlib, no extra dependency, and a
// faithful round-trip is all a deletion record needs.
type TombstoneRecord struct {
	InfoHash  string    `json:"infoHash"`
	DeletedAt time.Time `json:"deletedAt"`
}

// tombstoneTTL is the duration a deletion tombstone is kept before it is
// eligible for pruning.
//
// Rationale: RD fair-use caps have been observed to last days (3+ days
// sustained in production). A short TTL would re-open the re-adopt loop in
// exactly the scenario this tombstone must survive. The "long TTL blocks a
// legit re-grab" downside is neutralised because AddNewTorrent clears the
// tombstone on an explicit re-grab, so the risk is asymmetric - err long. A
// fixed constant is used rather than a manager-side window because the
// self-heal check runs at the storage layer where no runtime config exists.
const tombstoneTTL = 7 * 24 * time.Hour

// isExpired reports whether a tombstone has aged past tombstoneTTL.
func isExpired(r *TombstoneRecord) bool {
	return time.Since(r.DeletedAt) >= tombstoneTTL
}

// putTombstoneRecord marshals and persists a TombstoneRecord keyed by lowercased
// infohash. Separated from PutTombstone so tests can inject backdated records.
func (s *Storage) putTombstoneRecord(key string, r *TombstoneRecord) error {
	data, err := json.Marshal(r)
	if err != nil {
		return err
	}
	return s.tombstone.Put(strings.ToLower(key), data, nil)
}

// PutTombstone records a deletion tombstone for the given infohash keyed by
// lowercased infohash. Mirrors UpdateQueue's keying convention (strings.ToLower)
// so a re-deletion of the same hash de-dupes rather than accumulating duplicates.
func (s *Storage) PutTombstone(infohash string) error {
	return s.putTombstoneRecord(infohash, &TombstoneRecord{
		InfoHash:  infohash,
		DeletedAt: time.Now(),
	})
}

// IsTombstoned reports whether the given infohash has an active (non-expired)
// deletion tombstone. Case-insensitive: the key is always lowercased before
// lookup. Expired tombstones are lazily removed (self-heal) on read.
func (s *Storage) IsTombstoned(infohash string) bool {
	data, err := s.tombstone.Get(strings.ToLower(infohash))
	if err != nil {
		return false
	}
	var rec TombstoneRecord
	if err := json.Unmarshal(data, &rec); err != nil {
		return false
	}
	if isExpired(&rec) {
		// Lazy self-heal: best-effort delete of the expired record. Mirrors the
		// PersistedAt self-heal pattern in DrainPersistedRequeue.
		_ = s.DeleteTombstone(infohash)
		return false
	}
	return true
}

// DeleteTombstone removes the deletion tombstone for the given infohash.
func (s *Storage) DeleteTombstone(infohash string) error {
	return s.tombstone.Delete(strings.ToLower(infohash))
}

// ForEachTombstone iterates every persisted tombstone record. A decode failure
// on one record is skipped (best-effort) so a single corrupt entry can't block
// iteration of the rest.
//
// Known interaction: the dead errors.Is at hybrid/store.go:434 can truncate
// ForEach under concurrent delete, so a prune pass may under-collect. Harmless
// here - it self-heals on the next sweep, and IsTombstoned uses Get (not
// ForEach) so re-adoption-blocking correctness is unaffected.
func (s *Storage) ForEachTombstone(fn func(key string, r *TombstoneRecord) error) error {
	return s.tombstone.ForEach(func(key string, value []byte) error {
		var rec TombstoneRecord
		if err := json.Unmarshal(value, &rec); err != nil {
			return nil // skip corrupt records, best-effort
		}
		return fn(key, &rec)
	})
}

// PruneExpiredTombstones removes all tombstones whose TTL has elapsed and
// returns the count of pruned records. Keys are collected first, then deleted
// outside the ForEach callback to avoid mutating the store during iteration.
func (s *Storage) PruneExpiredTombstones() int {
	var expired []string
	_ = s.ForEachTombstone(func(key string, r *TombstoneRecord) error {
		if isExpired(r) {
			expired = append(expired, key)
		}
		return nil
	})
	for _, key := range expired {
		_ = s.DeleteTombstone(key)
	}
	return len(expired)
}
